name: 'Setup Pashmak'
description: 'Setup Pashmak programming language in your workflow'

inputs:
  pashmak-version:
    description: 'Version of Pashmak that you want to install'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        ${{ github.action_path }}/linux.sh ${{ inputs.pashmak-version }}
      if: runner.os == 'Linux'
      shell: bash
    - run: |
        ${{ github.action_path }}/macos.sh ${{ inputs.pashmak-version }}
      if: runner.os == 'macOS'
      shell: bash
    - run: |
        ${{ github.action_path }}/windows.sh ${{ inputs.pashmak-version }}
      if: runner.os == 'Windows'
      shell: bash
