name: 'Setup Pashmak'
description: 'Setup Pashmak programming language in your workflow'

inputs:
  pashmak-version:
    description: 'Version of Pashmak that you want to install'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          ${{ github.action_path }}/linux.sh ${{ inputs.pashmak-version }}
        elif [ "$RUNNER_OS" == "macOS" ]; then
          ${{ github.action_path }}/macos.sh ${{ inputs.pashmak-version }}
        elif [ "$RUNNER_OS" == "Windows" ]; then
          ${{ github.action_path }}/windows.sh ${{ inputs.pashmak-version }}
      shell: bash
