name: 'Setup Pashmak'
description: 'Setup Pashmak programming language in your workflow'

inputs:
  pashmak-version:
    description: 'Version of Pashmak that you want to install'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo ${{ github.action_path }}/scripts/linux.sh ${{ inputs.pashmak-version }}
        elif [ "$RUNNER_OS" == "macOS" ]; then
          sudo ${{ github.action_path }}/scripts/macos.sh ${{ inputs.pashmak-version }}
          cd pashmak
          sudo make install
          pashmak --version
        elif [ "$RUNNER_OS" == "Windows" ]; then
          ${{ github.action_path }}/scripts/windows.sh ${{ inputs.pashmak-version }}
        fi
      shell: bash
