name: 'Setup Pashmak'
description: 'Setup Pashmak programming language in your workflow'

inputs:
  pashmak-version:
    description: 'Version of Pashmak that you want to install'
    required: true

runs:
  using: "composite"
  steps:
    - run: ./unix.sh ${{ inputs.pashmak-version }}
      shell: bash
