name: 'Setup Pashmak'
description: 'Setup Pashmak programming language in your workflow'

inputs:
  pashmak-version:
    description: 'Version of Pashmak that you want to install'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo ${{ github.action_path }}/scripts/linux.sh ${{ inputs.pashmak-version }}
        elif [ "$RUNNER_OS" == "macOS" ]; then
          sudo ${{ github.action_path }}/scripts/macos.sh ${{ inputs.pashmak-version }}
          cd pashmak
          sudo cp ./dist/pashmak /usr/local/bin
          pashmak --info
        elif [ "$RUNNER_OS" == "Windows" ]; then
          wget https://github.com/pashmaklang/pashmak/archive/v${{ inputs.pashmak-version }}.zip -O pashmak.zip
          unzip pashmak.zip
          mv pashmak-* pashmak
          cd pashmak
          python -m pip install pyinstaller
          python -m PyInstaller src/pashmak.py
          ./dist/pashmak.exe --info
        fi
      shell: bash
